# The first case will return 3 for the value of x.
# The second case will trigger an error because x is initialized in the scope of the do block.
# Therefore x is not accessable outside of that scope.
